### ISSUE TITLE
faulty rebar file?

### ISSUE THREAD

**Issue by edwardt** [madtrick/wsecli#8]
{deps, [
  {espec, ".*", {git, "https://github.com/lucaspiller/espec.git", {branch, "master"}}},
  {cucumberl, "0.0.5", {git, "git@github.com:madtrick/cucumberl.git", {branch, master}}},   <---

should this be https://github.com:madtrick/cucumberl.git   ?????

since you are trying to use https all the way?

thanks

**Comment by madtrick** [comment]
Yep. You are right. Fixed in c7c2b2cb5856c8b552d96886489d81efb20e32a3

Thanks : )
