### ISSUE TITLE
sending binary is broken

### ISSUE THREAD

**Issue by skvamme** [madtrick/wsecli#9]
In cowboy log:
    `Message was {text,<<255,3,0,3,0,0,7,34,67,77>>}`

and crashes obviously. Well Cowboy doesn't crash of course but my session do.

In my code: `wsecli:send(<<255,3,0,3,0,0,7,34,67,77>>),`

I have checked framing opcode with wireshark on the outgoing frame from wsecli and it is (0x01 text) and should be (0x02 binary)

Temporary solution in wsecli.erl:

```
  open({send, Data}, StateData) ->
  case is_list(Data) of
      true -> Message = wsock_message:encode(Data, [mask, text]), io:format("Data is text: ~p~n",[Data]);
      _ -> Message = wsock_message:encode(Data, [mask, binary]), io:format("Data is binary: ~p~n",[Data])
  end,
  case gen_tcp:send(StateData#data.socket, Message) of
    ok ->
      ok;
    {error, Reason} ->
      (StateData#data.cb#callbacks.on_error)(Reason)
  end,
  {next_state, open, StateData}.
```

**Comment by madtrick** [comment]
Fixed in 68e3f4ff665d7fb3e9a3869036ca3da8f43c7437. Sorry for the long time until this was fixed.
